#!/usr/bin/python
import csv


def main():
    filename = 'blog-gender-dataset.csv'
    dataSet = loadCsv(filename)
    size = int(len(dataSet) * 0.70)

    train_dataSet = dataSet[0:size]
    test_dataSet = dataSet[size:]

    # separated = {'m': [], 'f': []}
    # for row in train_dataSet:
    #     separated[row[0]].append(row[1])

    sexes = {}
    for row in train_dataSet:
        sex = row[0]
        if sex in sexes:
            sexes[sex] += 1
        else:
            sexes[sex] = 1


    # for i in range(size):
    #     train_dataSet.append(dataSet[i])


    # print('Loaded data file {0} with {1} rows').format(filename, len(dataSet))
    print(dataSet[0][0]) #contains the gender - m/f
    # print(dataSet[0][1]) #contains the entire text


def loadCsv(filename):
    lines = csv.reader(open(filename, "rb"))
    dataSet = list(lines)
    newDataSet = []
    for i in range(len(dataSet)):
        sex = dataSet[i][0].strip()
        if sex is not '':
            a = set(dataSet[i][1].split(' '))
            a = [x for x in a if x not in [' ', '']]
            row = [sex, a]
            newDataSet.append(row)

    return newDataSet



def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet = []
    copy = list(dataset)
    while len(trainSet) < trainSize:
        index = random.randrange(len(copy))
        trainSet.append(copy.pop(index))
    return [trainSet, copy]


# separated = {}
# for i in range(len(dataset)):
#     vector = dataset[i]
#     if (vector[-1] not in separated):
#         separated[vector[-1]] = []
#     separated[vector[-1]].append(vector)
# return separated

main()